In [50]:
import requests
import shrimpy
import json
import pandas as pd

In [39]:
public_key = '9feb6543757418820ebe62b5bb2ca5e3aaef013ea172ca13c31a1147408a559c'
secret_key = 'b2c814e47326a6b969848b49248d6248245a0e5bc86beab6a65ccfa6ffbfffda1637ede2d89298153d207f0028f472cafb8ad1bae37358acc54da2832c1fbff0'
client = shrimpy.ShrimpyApiClient(public_key, secret_key)

In [48]:
btc_data = client.get_historical_candles(
    'Bittrex',
    'BTC',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)

eth_data = client.get_historical_candles(
    'Bittrex',
    'ETH',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)



ada_data = client.get_historical_candles(
    'Bittrex',
    'ADA',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)





xrp_data = client.get_historical_candles(
    'Bittrex',
    'XRP',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)


ltc_data = client.get_historical_candles(
    'Bittrex',
    'LTC',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)

trx_data = client.get_historical_candles(
    'Bittrex',
    'TRX',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)

In [109]:
usdt_data = client.get_historical_candles(
    'Bittrex',
    'USDT',
    'USD',
    '2019-03-20T00:00:00.000Z',
    '2021-03-20T00:00:00.000Z',
    1000,
    '1d'
)

In [110]:
btc_df = pd.DataFrame(btc_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
btc_df.set_index(pd.to_datetime(btc_df['time'], infer_datetime_format=True), inplace=True)
btc_df.drop(columns = 'time', inplace = True)

eth_df = pd.DataFrame(eth_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
eth_df.set_index(pd.to_datetime(eth_df['time'], infer_datetime_format=True), inplace=True)
eth_df.drop(columns = 'time', inplace = True)

ada_df = pd.DataFrame(ada_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
ada_df.set_index(pd.to_datetime(ada_df['time'], infer_datetime_format=True), inplace=True)
ada_df.drop(columns = 'time', inplace = True)

usdt_df = pd.DataFrame(usdt_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
usdt_df.set_index(pd.to_datetime(usdt_df['time'], infer_datetime_format=True), inplace=True)
usdt_df.drop(columns = 'time', inplace = True)

xrp_df = pd.DataFrame(xrp_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
xrp_df.set_index(pd.to_datetime(xrp_df['time'], infer_datetime_format=True), inplace=True)
xrp_df.drop(columns = 'time', inplace = True)

ltc_df = pd.DataFrame(ltc_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
ltc_df.set_index(pd.to_datetime(ltc_df['time'], infer_datetime_format=True), inplace=True)
ltc_df.drop(columns = 'time', inplace = True)

trx_df = pd.DataFrame(trx_data, columns=['open', 'high', 'low', 'close', 'volume', 'quoteVolume', 'time'])
trx_df.set_index(pd.to_datetime(trx_df['time'], infer_datetime_format=True), inplace=True)
trx_df.drop(columns = 'time', inplace = True)

In [111]:
btc_df["open"] = btc_df["open"].astype("float")
btc_df["high"] = btc_df["high"].astype("float")
btc_df["low"] = btc_df["low"].astype("float")
btc_df["close"] = btc_df["close"].astype("float")
btc_df["volume"] = btc_df["volume"].astype("float")
btc_df["quoteVolume"] = btc_df["quoteVolume"].astype("float")
btc_df.head()

eth_df["open"] = eth_df["open"].astype("float")
eth_df["high"] = eth_df["high"].astype("float")
eth_df["low"] = eth_df["low"].astype("float")
eth_df["close"] = eth_df["close"].astype("float")
eth_df["volume"] = eth_df["volume"].astype("float")
eth_df["quoteVolume"] = eth_df["quoteVolume"].astype("float")
eth_df.head()

ada_df["open"] = ada_df["open"].astype("float")
ada_df["high"] = ada_df["high"].astype("float")
ada_df["low"] = ada_df["low"].astype("float")
ada_df["close"] = ada_df["close"].astype("float")
ada_df["volume"] = ada_df["volume"].astype("float")
ada_df["quoteVolume"] = ada_df["quoteVolume"].astype("float")
ada_df.head()

usdt_df["open"] = usdt_df["open"].astype("float")
usdt_df["high"] = usdt_df["high"].astype("float")
usdt_df["low"] = usdt_df["low"].astype("float")
usdt_df["close"] = usdt_df["close"].astype("float")
usdt_df["volume"] = usdt_df["volume"].astype("float")
usdt_df["quoteVolume"] = usdt_df["quoteVolume"].astype("float")
usdt_df.head()

xrp_df["open"] = xrp_df["open"].astype("float")
xrp_df["high"] = xrp_df["high"].astype("float")
xrp_df["low"] = xrp_df["low"].astype("float")
xrp_df["close"] = xrp_df["close"].astype("float")
xrp_df["volume"] = xrp_df["volume"].astype("float")
xrp_df["quoteVolume"] = xrp_df["quoteVolume"].astype("float")
xrp_df.head()

ltc_df["open"] = ltc_df["open"].astype("float")
ltc_df["high"] = ltc_df["high"].astype("float")
ltc_df["low"] = ltc_df["low"].astype("float")
ltc_df["close"] = ltc_df["close"].astype("float")
ltc_df["volume"] = ltc_df["volume"].astype("float")
ltc_df["quoteVolume"] = ltc_df["quoteVolume"].astype("float")
ltc_df.head()

trx_df["open"] = trx_df["open"].astype("float")
trx_df["high"] = trx_df["high"].astype("float")
trx_df["low"] = trx_df["low"].astype("float")
trx_df["close"] = trx_df["close"].astype("float")
trx_df["volume"] = trx_df["volume"].astype("float")
trx_df["quoteVolume"] = trx_df["quoteVolume"].astype("float")
trx_df.head()

,open,high,low,close,volume,quoteVolume
time,,,,,,
2019-03-20 00:00:00+00:00,0.023,0.023,0.022,0.023,1.256708e+06,28011.148213
2019-03-21 00:00:00+00:00,0.023,0.023,0.021,0.022,1.008765e+06,22621.845503
2019-03-22 00:00:00+00:00,0.023,0.023,0.022,0.023,5.028059e+05,11313.313406
2019-03-23 00:00:00+00:00,0.023,0.024,0.023,0.024,1.862948e+06,44387.898148
2019-03-24 00:00:00+00:00,0.024,0.025,0.023,0.023,1.639674e+06,38217.320761

{'open': '0.0230000000000000',
 'high': '0.0230000000000000',
 'low': '0.0220000000000000',
 'close': '0.0230000000000000',
 'volume': '1256707.8250410600000000',
 'quoteVolume': 28011.14821296856,
 'time': '2019-03-20T00:00:00.000Z'}